### ISSUE TITLE
SWT error 

### ISSUE THREAD

**Issue by zmsp** [gondoi/davmail-docker#1]
When I try to run using 
`nohup /usr/local/davmail/davmail.sh /usr/local/davmail/davmail.properties &` 
inside docker container it gives me this error. I don't know if you are still maintaining it. 

```
Exception in thread "SWT" org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
    at org.eclipse.swt.widgets.Display.create(Unknown Source)
    at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at davmail.ui.tray.SwtGatewayTray$5.run(SwtGatewayTray.java:202)
```

**Comment by gondoi** [comment]
No I have not maintained this for a while since I have not had the need to run this. I could certainly give updating this a shot. If you would like to try and clean it up, I'd be willing to bet it needs to be updated to the latest version of davmail since this `Dockerfile` is pulling down a pretty old version.
